### ISSUE TITLE
Can I help ?

### ISSUE THREAD

**Issue by ghost** [jonboj/mdcdalight#1]
I also want dart with MDC.
Saw the GitHub issue about dart web components ending.

So if you can make a short list of Todo I can start helping...

**Comment by ghost** [comment]
So far it looks like the base is pretty complete.

**Comment by jonboj** [comment]
Thanks for your interest!

As also remarked in this issue https://github.com/jonboj/mdcdalight/issues/2
mdcdalight is a on very simple/rough scale an integration between dart-sdk, web components and mdc web. To continue work on mdcdalight only really makes sense if dart-sdk supports web components v1. Actually v0 maybe get deprecated from Chrome within an year 
https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/h-JwMiPUnuU/sl79aLoLBQAJ
When web components v0 gets deprectated and dart-sdk don't have support for v1, mdcdalight will only be supported non updated versions of different browsers.

I will close the issue. Anyhow if you have any ideas to projects with mdc web and dart you are very welcome to ping me on the gitter channel https://gitter.im/dart-lang/TALK-general. At the moment I don't have so much time for community projects, but will very likely join disscussions, debuging or other more less time consuming tasks than implementation.
